### ISSUE TITLE
Run on Android?

### ISSUE THREAD

**Issue by resetter** [FreeTHX/pywakeps4onbt#1]
Hi, have been trying to run this script on android via QPython and also termux but have had no success, is this possible?

**Comment by FreeTHX** [comment]
Hi @resetter 

Once the package is installed, could you please run the following python code :
`import wakeps4onbt

adapterdevid = wakeps4onbt.get_devid_from_devname(0)
bt_socket = wakeps4onbt.hci_open_dev(adapterdevid)
manufacturer = wakeps4onbt.hci_read_local_manufacturer(bt_socket)
wakeps4onbt.hci_close_dev(bt_socket)
print(manufacturer)`

this will give us the manufactuer id of the bt device. (to confirm or not the support for this device)

**Comment by resetter** [comment]
Hey, ok I tried running those commands and ran into the same issue, my best guess is that bluetooth, or at least raw sockets in bluetooth are not supported or not implemented in android. Here is the output:

`/data/user/0/org.qpython.qpy/files/bin/qpytho n3.sh && exit
n.qpy/files/bin/qpython3.sh && exit         < Python 3.11.0 (main, Oct 29 2022, 21:50:32) [ Clang  14.0.6 (https://android.googlesource.co m/toolchain/llvm-project 4c603efb0 on linux
Type "help", "copyright", "credits" or "licen se" for more information.
>>> import wakeps4onbt                                                                             >>> adapterdevid = wakeps4onbt.get_devid_from_devname(0)
>>> bt_socket = wakeps4onbt.hci_open_dev(adapterdevid)                                             Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/user/0/org.qpython.qpy/files/lib/python3.11/site-packages/wakeps4onbt/wakeps4onbt.py ", line 46, in hci_open_dev
    dd = socket.socket(socket.AF_BLUETOOTH, socket.SOCK_RAW, socket.BTPROTO_HCI)
                       ^^^^^^^^^^^^^^^^^^^
AttributeError: module 'socket' has no attribute 'AF_BLUETOOTH'`

**Comment by FreeTHX** [comment]
Hi @resetter 
Indeed, python 3.11 should support AF_BLUETOOTH.
But your python runtime is probably built  without Bluetooth socket support.
Could you please check with the following command ?
`python3 -m sysconfig | grep BLUE`
or in the python shell
`import sysconfig`
`print(sysconfig.get_config_vars())`
and tell me if HAVE_BLUETOOTH_BLUETOOTH_H or HAVE_BLUETOOTH_H are enabled ?

**Comment by resetter** [comment]
Yeah it seems both are disabled in each of the python IDEs for Android that I have tried.
Seems to be a limitation of Android I think.

**Comment by FreeTHX** [comment]
Or a limitation of this specific python version.
This issue should be re-opened once the bluetooth socket is available in python for Android.
